name: confined-shell
adopt-info: miriway
summary: A minimal Mir based confined shell for testing support for such things
description: |
  The current iteration is based on Miriway, swaybg and wofi.
  
  To activate the wofi launcher press `Meta+a`. This will show snaps publishing a
  .desktop file, but only Wayland based snaps will run successfully.
  
  To exit the shell press Ctrl-Alt-BkSp (long press if apps are running)
  
  For the greeter (e.g. GDM) to recognise the confined-shell session run:
  
      /snap/confined-shell/current/bin/setup.sh
confinement: strict
grade: devel
base: core24
build-base: devel

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  PATH: $SNAP/usr/local/bin/:$SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # XDG config
  XDG_DATA_DIRS:   $SNAP/usr/share
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep for Mir
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/mir/server-platform
  # graphics
  LIBINPUT_QUIRKS_DIR:       $SNAP/usr/share/libinput
  # Setup XKB
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0
  /usr/share/drirc.d:  # Used by mesa-2404 for app specific workarounds
    symlink: $SNAP_COMMON/gpu-2404/usr/share/drirc.d
  /usr/share/X11/XErrorDB:   # Used by gpu-2404 for X11
    symlink: $SNAP_COMMON/gpu-2404/usr/share/X11/XErrorDB
  # these could be avoided through a desktop plug
  /etc/gtk-3.0:
    bind: $SNAP/etc/gtk-3.0
  /etc/fonts:
    bind: $SNAP/etc/fonts

apps:
  confined-shell:
    command-chain:
      - bin/run-shell
      - bin/gpu-2404-wrapper
    command: usr/local/bin/miriway
    desktop: usr/share/wayland-sessions/confined-shell.desktop
    slots:
      - wayland
    plugs:
      - desktop-launch
      - login-session-control
      - hardware-observe
      - opengl
      - x11
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:/var/lib/snapd/desktop

parts:
  miriway:
    source: https://github.com/Miriway/Miriway.git
    override-pull: |
      craftctl default
      server_version=`git rev-list --count HEAD`
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      # work around https://github.com/diddlesnaps/snapcraft-multiarch-action/issues/22
      git config --global --add safe.directory ${CRAFT_PROJECT_DIR}
      recipe_version=`git -C ${CRAFT_PROJECT_DIR} rev-list --count HEAD`
      craftctl set version=$server_version-mir$mir_version-snap$recipe_version
      # if echo $mir_version | grep -e '+dev' -e '~rc' -q; then craftctl set grade=devel; else craftctl set grade=stable; fi
    plugin: cmake
    build-packages:
      - build-essential
      - pkg-config
      - libmiral-dev
      - g++
    stage-packages:
      - mir-graphics-drivers-desktop
      - mir-graphics-drivers-nvidia
      # Stage libmiral<n> indirectly as we cannot (since core22) do `try:/else:`
      - libmiral-dev
    prime:
      # Do not prime the `-dev` part of libmiral-dev, we don't need it (just the libmiral<n> dependency)
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/libmir*.so
      - -usr/share/wayland-sessions/miriway.desktop

  wofi:
    plugin: nil
    stage-packages:
      - wofi

  swaybg:
    plugin: nil
    stage-packages:
      - swaybg
      - ubuntu-wallpapers

  yambar:
    plugin: meson
    meson-parameters:
      - -Dbackend-x11=disabled
      - -Dbackend-wayland=enabled
    build-packages:
      - meson
      - ninja-build
      - wayland-protocols
      - libasound2-dev
      - libfcft-dev
      - libfontconfig-dev
      - libharfbuzz-dev
      - libinotifytools0-dev
      - libjson-c-dev
      - libmpdclient-dev
      - libpixman-1-dev
      - libtllist-dev
      - libudev-dev
      - libwayland-dev
      - libyaml-dev
      - scdoc
      - flex
      - bison
    source: https://codeberg.org/dnkl/yambar.git
    source-tag: 1.9.0
    source-depth: 1
    stage-packages:
      - fonts-font-awesome
      - fonts-ubuntu
      - libasound2
      - libfcft4t64
      - libjson-c5
      - libmpdclient2t64
      - libpixman-1-0
      - libudev1
      - libwayland-client0
      - libyaml-0-2

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  glue:
    plugin: dump
    source: glue

  env:
    plugin: cmake
    source: env

  misc:
    plugin: nil
    stage-packages:
    - libgdk-pixbuf2.0-bin # GDK pixbuf
    - libglib2.0-0t64
    - libgtk-3-common # GTK schemas
    build-packages:
      - libglib2.0-0t64
      - libgdk-pixbuf2.0-0
      - librsvg2-dev # So the libpixbufloader-svg.so loader can be loaded by gdk-pixbuf-query-loaders
    override-build: |
      craftctl default
      update-mime-database $CRAFT_PART_INSTALL/usr/share/mime
    override-prime: |
      craftctl default
      # Compile the gsettings schemas
      /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/glib-2.0/glib-compile-schemas "$CRAFT_PRIME/usr/share/glib-2.0/schemas"
      # Index the pixbuf loaders
      GDK_PIXBUF_MODULEDIR=$CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gdk-pixbuf-2.0/2.10.0/loaders \
      "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache"
      sed s!$CRAFT_PRIME!!g --in-place "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache"

  gpu-snap:
    after:
      - miriway
      - env
      - yambar
      - wofi
      - swaybg
      - icons
      - glue
      - misc
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      rm -rf ${CRAFT_PRIME}/{bug,doc,lintian,man}
    prime:
      - bin/gpu-2404-wrapper

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    # default-provider: mesa-2404

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

package-repositories:
  - type: apt
    ppa: mir-team/release
