#!/bin/bash

snap_core=$(sed -n 's/.*snap_core=\([^ ]*\).*/\1/p' /proc/cmdline)

# If 'vt.handoff' is set, Mir only starts first time on the default VT. (#779)
# Until we understand and fix properly, set the config the way that works.
vt=$(sed -n 's/.*vt.handoff=\([^ ]*\).*/\1/p' /proc/cmdline)
if [ -z "${snap_core}" ] || [ -z "$vt" ]
then snapctl set vt=5
else snapctl set vt=0
fi

# On Ubuntu Core18 we default to software cursor
if [[ "${snap_core}" =~ core18.*snap ]]
then snapctl set cursor=software
else snapctl set cursor=auto
fi

snapctl set display-layout=default

# GDK pixbuf setup
# For unknown reasons LD_LIBRARY_PATH is just "${SNAP}/graphics/lib" when the hook executes
LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:${SNAP}/graphics/lib:${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/lib/x86_64-linux-gnu:${SNAP}/usr/lib/x86_64-linux-gnu
"$GDK_PIXBUF_QUERY_LOADERS" > "$GDK_PIXBUF_MODULE_FILE"
